markdown: kramdown
include:
  - "_*"
  - "api"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

defaults:
  - scope:
      path: "api"
    values:
      render_with_liquid: false
