title: React OL Documentation
description: A lightweight React wrapper for OpenLayers â€” build interactive maps declaratively using components and hooks.
baseurl: "/react-ol"
url: "https://uniteamou.github.io"

theme: jekyll-theme-cayman

markdown: kramdown

include: docs/guides
exclude:
  - node_modules
  - package.json
  - package-lock.json
